### PR TITLE
Fix async read size bugs

### PR DESCRIPTION
**Pull request by aiudirog**
- Make sure TAsyncSocket reads all of the data
- Ask for the min size, not the max in TAsyncBufferedTransport.read()

### CODE REVIEW

**Comment by ethe** [comment]
Do not forget to handle `IncompleteReadError`, re-raise it as `TTransportException.END_OF_FILE` is a good idea.

**Comment by aiudirog** [comment]
Good catch, thanks!

**Comment by ethe** [comment]
Please see #102, this part of code was not written by me so I spent a lot of time to understand it, I think it may conform the origin design. The key is, using `min` would lose the cache from buffer.

**Comment by ethe** [comment]
Maybe you can test your cases with my branch, thank you.

**Comment by aiudirog** [comment]
I'll look into it in the morning, thanks for the quick responses!

**Comment by aiudirog** [comment]
Closed in favor of #102

**Pull request closed without merging**
