### PR TITLE
enable include_package_data in setup.py

### PR DESCRIPTION
**Pull request by aisk**
The original problem is the `.pyx` and `.pxd` files was not packaged in current versions, so it's not possible for extending the cython based classes (cython need source files to compile) in another package besides thriftpy2.

I saw there was a `MANIFEST.in`,but the `include_package_data` is not set in `setup.py`, according to 
[setuptoos 's documents](https://setuptools.readthedocs.io/en/latest/setuptools.html#including-data-files), it should be set to make `MANIFEST` to take efforts. And seems the `package_data` field is duplicated if we enable `include_package_data`.

### CODE REVIEW

**Comment by ethe** [comment]
If you want to package thriftpy2 manually, using `make build` instead, mentioned that you need to install `Cython` correctly. I think `make build`has already processed the `.pyx` and `.pxd` file.

**Comment by aisk** [comment]
No, I want using thriftpy2 as a pip dependence, and extend some classes which was written in cython.

**Comment by aisk** [comment]
And I think it's a bug that `MANIFEST.in` was there and take no efforts.

**Comment by ethe** [comment]
Could you please tell me how can I reproduce your issue?

**Comment by aisk** [comment]
Running `pip install thriftpy2` to install latest thriftpy2, and take a look and site-packages, the `pyx` files was gone, only the `.so` exists. If we want subclass a cython class, the `pyx` must exists.

Install my branch using `pip install --user git+https://github.com/aisk/thriftpy2.git#branch=fix-package-data`, the `pyx` exists as expected.

**Comment by ethe** [comment]
That's true, thank you.

**Comment by aisk** [comment]
Hi @ethe , another question, what's the release schedule of thriftpy2? My package is reply on this and #60.

**Comment by ethe** [comment]
@aisk I will release it later this week, unfortunately there is not a release schedule of thriftpy2 yet.

**Comment by aisk** [comment]
Cool, thanks for help!

**Pull request merged**
