### PR TITLE
Fix typo word

### PR DESCRIPTION
**Pull request by truebit**
fix issue #122

### CODE REVIEW

**Comment by aisk** [comment]
I think we should have an alias for `ThriftGrammerError` for don't break unit test and users' codes.

And maybe we can declare a module level `__getattr__` which descibed in [PEP 562](https://www.python.org/dev/peps/pep-0562/), for users who were using Python3.7 and latter versions can got a deprecated warning.

**Comment by truebit** [comment]
IMHO, this change do not need to consider backward compatibility due to the ROI of this change. Anyone used old `ThriftGrammerError` would be easy to find out the changed class name.

**Comment by ethe** [comment]
I think it would be better to keep backward compatibility, I have to release a minor version after this pull request be merged, it is not necessary

**Comment by aisk** [comment]
The only cocern is the error message is changed, but I think this will only affect thriftpy2's test.

**Review by ethe — APPROVED** [review]

**Pull request merged**
