### PR TITLE
Fix tests and travis build

### PR DESCRIPTION
**Pull request by microdog**
https://travis-ci.org/microdog/thriftpy2/builds/433592780

### CODE REVIEW

**Comment by ethe** [comment]
No need to merge this any more.

**Comment by microdog** [comment]
According to https://github.com/travis-ci/travis-ci/issues/9815#issuecomment-401125783, the `3.7-dev` is using a fairly dated beta release that doesn't reflect the RC/stable 3.7, so it should not be used.

Also, there is a [behaviour change](https://bugs.python.org/issue32706#msg312895) in the ssl module which should be handled. I just updated the test to adopt this change, and I am not sure if the server or client code should be updated to adopt this.

**Comment by ethe** [comment]
Please resolve conflicts, thanks! I don't think we need to revert #10

**Comment by microdog** [comment]
Green. 🍻

**Pull request merged**
