### PR TITLE
Binary support

### PR DESCRIPTION
**Pull request by JonnoFTW**
Added binary support per #156 

I've added some more tests to cover more cases surrounding binary encodings. If you pass a string to a binary field, it will come out as a bytes type on the other end.

The work here builds off #163 , so that will probably need to be merged before this one.

### CODE REVIEW

**Comment by JonnoFTW** [comment]
@ethe are you able to look at this at some point?

**Comment by ethe** [comment]
I will take a look at it, could you please remove [WIP] in the title?

**Comment by JonnoFTW** [comment]
@ethe I have fixed the title.

**Review by ethe — APPROVED** [review]

**Comment by ethe** [comment]
I have a question, does it break the compatibility? If the user defines a binary type and treats it as a string before, what happened after this commit merged?

**Comment by ethe** [comment]
Maybe we should consider that only turn on this feature in JSON protocol, and do not modify others, or turn off it as default.

**Comment by JonnoFTW** [comment]
@ethe please check `tests/test_all_protocols_binary_field.py` for a test case on how binary fields are treated. I think the best behaviour would be that the type specified in the thrift file is what you get on the when deserializing.

If a string is passed to a binary field, when deserialised you always get a binary. Conversely, if a binary is passed to a string field, it should be stringified  (if possible) when deserializing.

**Pull request merged**
