### PR TITLE
Build a wheel as part of the Make build step so that it will be published to pypi

### PR DESCRIPTION
**Pull request by dbaxa**

### CODE REVIEW

**Comment by dbaxa** [comment]
cc @aisk

**Review by ethe — APPROVED** [review]

**Comment by ethe** [comment]
Approved, thank you.

**Comment by dbaxa** [comment]
@ethe how do we merge this :-) ?

**Comment by aisk** [comment]
I think maybe we have future works to do, since thriftpy2 have C extensions, the `bdist_wheel` only produce wheel package for current python version * CPU arch * OS. I think we need a CI cluster to build the wheels.

**Pull request merged**
