### PR TITLE
try to fix issue #172 when system locale not set

### LINKED ISSUE #172: When environment locale not set, thrift parser would throw UnicodeDecodeError due to using "open" directly.
```
File "/Users/someone/Documents/code/pycharm/test/venv/lib/oython3.6/site-packages/thriftpy2/parser/ init py", line 33, in load
include_dir=include_dir)
File "/Users/someone/Documents/code/oycharm/test/venv/lib/oython3.6/site-packaaes/thriftoy2/oarser/oarser.py", line 577, in parse data = fh.read ()
File "/Users/someone/.pyenv/versions/3.6.0/lib/python3.6/encodinqs/ascii.py'", line 26, in decode
return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte @xe6 in position 113: ordinal not in range(128)
```

prboblematic code  in parser.py:
```
    url_scheme = urlparse(path).scheme
    if url_scheme == 'file':
        with open(urlparse(path).netloc + urlparse(path).path) as fh:
            data = fh.read()
    elif len(url_scheme) <= 1:
        with open(path) as fh:
            data = fh.read()
    elif url_scheme in ('http', 'https'):
        data = urlopen(path).read()
    else:
        raise ThriftParserError('thriftpy2 does not support generating module '
                                'with path in protocol \'{}\''.format(
                                    url_scheme))
```

Possible solution:
check if python2 or python3, py3 supports open(encoding=xxx), py2 could use io.open

### PR DESCRIPTION
**Pull request by truebit**
try to fix #172

### CODE REVIEW

**Comment by ethe** [comment]
Thank you, please fix the CI error

**Comment by truebit** [comment]
I have fixed Python2 test error.  But the python 3.4 one seems environment related:"ImportError: No module named 'typing'".

**Comment by truebit** [comment]
The py3.4 issue was addressed in #175.
You could firstly approve #175 and then approve this PR.

**Comment by truebit** [comment]
@ethe Could you please review this PR? this problem affects those machine which did not set LANG, especially in docker.

**Comment by truebit** [comment]
@ethe It seems Travis CI changed Open Source credits point assignment rules: "Owner Thriftpy does not have enough credits.", so all the ci checks failed to be executed. Maybe you should check ci settings.

Below is copied from FAQ of TravisCI:

>Where can I check my credit balance?
>
>You can check your credit balance by going to Settings -> Plan usage -> Credits. You can find a bar representing the subscribed credits pool and remaining credits. You can check the status of your Open Source Software (OSS) credits as well. 
>
>What if I am building open source?
>Each of the Travis CI Plans contains an amount of special OSS credits per month assigned to run builds only on public repositories. To find out more about it please contact the Travis CI support team. In the email please include:
>
>Your account name and your VCS provider (like travis-ci.com/github/[your account name] )
>How many credits (build minutes) you’d like to request (should your run out of credits again you can repeat the process to request more or to discuss a renewable amount)

**Comment by ethe** [comment]
Ok, I will try to fix CI or check it manually, this looks good to me.

**Comment by ethe** [comment]
I have no idea how CI is failed
image

**Pull request merged**
