### PR TITLE
add url support as optional argument to make_client

### PR DESCRIPTION
**Pull request by iamsudip**

### CODE REVIEW

**Comment by ethe** [comment]
I think it is better to change the protocol type in the URL, `https://` and `tcp://` does not make sense. In my opinion, using `thrift://` is better because of the usual practice.

**Comment by iamsudip** [comment]
> I think it is better to change the protocol type in the URL, `https://` and `tcp://` do not make sense. In my opinion, using `thrift://` is better because of the usual practice.

Agree. Let me change that.

**Comment by iamsudip** [comment]
@ethe Have a look now! Made the changes and added more tests to increase coverage ;)

**Comment by ethe** [comment]
Merged, thank you.

**Pull request merged**
